'use strict';

import dotenv from 'dotenv'
dotenv.config({ silent: true });

import path from 'path';
import FileWriter from './tools/file-writer';
import ip from 'quick-local-ip';

var HOST = process.env.NODE_ENV === 'development' ? 'localhost' : ip.getLocalIP4();

var env = [
    '###',
    '### WARNING: This file is generated by ' + path.basename(__filename) + ' - do not edit manually!',
    '###',
    'HOST=' + HOST,
    'PORT=29957',
    'API_ROOT=api',
    'AMQP=false',
    'AUTH0_CLIENT_ID=mufc9w7SiOb3A5SbxEAQgGJtwJgwsya9',
    'AUTH0_CLIENT_SECRET=',
    'AUTH0_DOMAIN=generictest35.auth0.com',
    'AUTH0_CALLBACK_URL=http://localhost:8080/auth'
];


module.exports = function () {
    FileWriter.write('.env', env.join('\n'));
};